### ISSUE TITLE
dagexplorer showing incorrect balance

### ISSUE THREAD

**Issue by flannoo** [StardustCollective/dag-explorer-v2#48]
Hello,

[Dagexplorer](https://mainnet.dagexplorer.io/address/DAG3jrVW4ys1g2ve98qhvMoAUSqgwEBdCggN6NHz) is showing an incorrect balance for the wallet DAG3jrVW4ys1g2ve98qhvMoAUSqgwEBdCggN6NHz
This wallet should have a balance of 0 DAG, but dagexplorer shows balance of 27,267,227.44627029 DAG

You can check the balance against the node API here (make sure to set the `Accept` http header to `application/json`): 
```http://l0-lb-mainnet.constellationnetwork.io/dag/DAG3jrVW4ys1g2ve98qhvMoAUSqgwEBdCggN6NHz/balance```
This shows a (correct) balance of 0.

Not sure if there are other wallets showing incorrect balances, but thought it was worth looking into, which is why I opened this issue.

**Comment by AlexBrandes** [comment]
Hey @flannoo - thanks for reporting this. 

It appears this was an issue with the indexer for the Block Explorer API which is the backend that the DAG Explorer relies on for balance data. I passed the message along to that team and they were able to reindex your address and a few others that had the same issue. Your balance is updated to correctly display zero on the DAG Explorer now.
