### ISSUE TITLE
Feature Request: Display Snapshot Rewards 

### ISSUE THREAD

**Issue by flannoo** [StardustCollective/dag-explorer-v2#49]
Hello,

Would it be possible to include the rewards generated by a snapshot in the snapshot details on dagexplorer?
This makes it easier to audit and trace those kind of rewards.

## Global Snapshots
Example snapshot 1064963

On the page  [https://mainnet.dagexplorer.io/snapshots/1064963](https://mainnet.dagexplorer.io/snapshots/1064963), I'd like to see a new section called "Rewards" that displays all the rewards that were distributed in that snapshot, that contains a grid with the timestamp, currency, amount & destination address

This info can be retrieved through the API call [https://be-mainnet.constellationnetwork.io/global-snapshots/1064961/rewards](https://be-mainnet.constellationnetwork.io/global-snapshots/1064961/rewards)

## Metagraph Snapshots
Example snapshot 529835

On the page  [https://mainnet.dagexplorer.io/metagraphs/DAG0CyySf35ftDQDQBnd1bdQ9aPyUdacMghpnCuM/snapshots/529835](https://mainnet.dagexplorer.io/metagraphs/DAG0CyySf35ftDQDQBnd1bdQ9aPyUdacMghpnCuM/snapshots/529835), I'd like to see a new section called "Rewards" that displays all the rewards that were distributed in that snapshot, that contains a grid with the timestamp, currency, amount & destination address

This info can be retrieved through the API call [https://be-mainnet.constellationnetwork.io/currency/DAG0CyySf35ftDQDQBnd1bdQ9aPyUdacMghpnCuM/snapshots/529835/rewards](https://be-mainnet.constellationnetwork.io/currency/DAG0CyySf35ftDQDQBnd1bdQ9aPyUdacMghpnCuM/snapshots/529835/rewards)

This should be generic so it also works for future metagraphs.

This would be greatly appreciated!
Thanks!

Best regards

**Comment by juandavidkincaid** [comment]
Hi @flannoo this feature has been added, thanks for the suggestion, sorry the late response.
